import os
from dotenv import load_dotenv

load_dotenv()

# ── Database ────────────────────────────────────────────────
USE_SNOWFLAKE = os.getenv("USE_SNOWFLAKE", "false").lower() == "true"

# SQLite (development)
SQLITE_DB_PATH = os.getenv("SQLITE_DB_PATH", "warehouse.db")

# Snowflake (production)
SNOWFLAKE_CONFIG = {
    "account":   os.getenv("SNOWFLAKE_ACCOUNT", ""),
    "user":      os.getenv("SNOWFLAKE_USER", ""),
    "password":  os.getenv("SNOWFLAKE_PASSWORD", ""),
    "database":  os.getenv("SNOWFLAKE_DATABASE", "ECOMMERCE_DW"),
    "warehouse": os.getenv("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
    "schema":    os.getenv("SNOWFLAKE_SCHEMA", "PUBLIC"),
}

# ── Paths ────────────────────────────────────────────────────
RAW_DATA_DIR       = "data/raw"
PROCESSED_DATA_DIR = "data/processed"
SAMPLE_DATA_DIR    = "data/sample"
EXPORT_DIR         = "dashboard/exports"

# ── ETL ──────────────────────────────────────────────────────
BATCH_SIZE         = 1000       # rows per DB insert batch
SAMPLE_ROW_COUNT   = 10_000     # rows generated by generate_sample_data.py
